# Generated by Django 6.0 on 2026-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_alugados', models.DateField()),
                ('total_pago', models.IntegerField()),
                ('encerrado', models.BooleanField()),
            ],
        ),
    ]
