# Generated by Django 6.0 on 2026-01-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='dias_alugados',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='encerrado',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='total_pago',
        ),
    ]
