# Generated by Django 6.0 on 2026-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('disponivel', models.BooleanField()),
                ('estado', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
