# Generated by Django 6.0 on 2026-01-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedade', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propriedade',
            old_name='bairro',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='propriedade',
            name='rua',
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
