# Generated by Django 6.0 on 2026-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedade', '0003_rename_bairro_propriedade_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='propriedades/'),
        ),
    ]
